export const oldNewDistMap = {
  Agra: 'Agra',
  Ahmedabad: 'Ahmedabad',
  Ahmednagar: 'Ahmednagar',
  Akola: 'Akola',
  Aligarh: 'Aligarh',
  Ambala: 'Ambala',
  Amravati: 'Amravati',
  'Amreli district': 'Amreli',
  Anand: 'Anand',
  Anuppur: 'Anuppur',
  Araria: 'Araria',
  'Ashok Nagar': 'Ashoknagar',
  Aurangabad: 'Aurangabad',
  Azamgarh: 'Azamgarh',
  Balaghat: 'Balaghat',
  Banaskantha: 'Banas Kantha',
  Banda: 'Banda',
  'Bangalore Rural': 'Bengaluru Rural',
  'Bangalore Urban': 'Bengaluru Urban',
  Banka: 'Banka',
  Bankura: 'Bankura',
  Barmer: 'Barmer',
  Basti: 'Basti',
  Betul: 'Betul',
  Bhadrak: 'Bhadrak',
  Bhagalpur: 'Bhagalpur',
  Bhandara: 'Bhandara',
  Bharuch: 'Bharuch',
  Bhavnagar: 'Bhavnagar',
  Bhilwara: 'Bhilwara',
  Bhind: 'Bhind',
  Bhiwani: 'Bhiwani',
  Bhopal: 'Bhopal',
  Bijnor: 'Bijnor',
  Birbhum: 'Birbhum',
  Botad: 'Botad',
  Budaun: 'Budaun',
  Buldhana: 'Buldhana',
  Buxar: 'Buxar',
  'Charkhi Dadri': 'Charki Dadri',
  Chhindwara: 'Chhindwara',
  Chittoor: 'Chittoor',
  Chittorgarh: 'Chittorgarh',
  Cuttack: 'Cuttack',
  Dahod: 'Dahod',
  Damoh: 'Damoh',
  Dantewada: 'Dakshin Bastar Dantewada',
  Datia: 'Datia',
  Dausa: 'Dausa',
  Davanagere: 'Davangere',
  Dehradun: 'Dehradun',
  Deoria: 'Deoria',
  Dhamtari: 'Dhamtari',
  Dhenkanal: 'Dhenkanal',
  Dindori: 'Dindori',
  Doda: 'Doda',
  Durg: 'Durg',
  'East Delhi': 'East Delhi',
  Ernakulam: 'Ernakulam',
  Faridabad: 'Faridabad',
  Fatehpur: 'Fatehpur',
  Firozabad: 'Firozabad',
  Gandhinagar: 'Gandhinagar',
  Gaya: 'Gaya',
  Gonda: 'Gonda',
  Gondal: 'Rajkot',
  Gondia: 'Gondia',
  Gorakhpur: 'Gorakhpur',
  Gujarat: 'Gujarat',
  Gulbarga: 'Kalaburagi',
  Gwalior: 'Gwalior',
  Hapur: 'Hapur',
  Haridwar: 'Haridwar',
  Hassan: 'Hassan',
  Hissar: 'Hisar',
  Hooghly: 'Hooghly',
  Hoshangabad: 'Narmadapuram',
  Howrah: 'Howrah',
  Idukki: 'Idukki',
  Jabalpur: 'Jabalpur',
  Jaipur: 'Jaipur (Gramin)',
  Jajpur: 'Jajapur',
  Jalaun: 'Jalaun',
  Jalgaon: 'Jalgaon',
  Jalna: 'Jalna',
  Jalore: 'Jalore',
  Jalpaiguri: 'Jalpaiguri',
  Jammu: 'Jammu',
  Jamnagar: 'Jamnagar',
  Jamui: 'Jamui',
  'Janjgir-Champa': 'Janjgir-Champa',
  Jashpur: 'Jashpur',
  Jhansi: 'Jhansi',
  Jodhpur: 'Jodhpur (Gramin)',
  Junagadh: 'Junagadh',
  Kaimur: 'Kaimur (Bhabua)',
  Kandhamal: 'Kandhamal',
  Kannauj: 'Kannauj',
  Kanpur: 'Kanpur Nagar',
  Kathua: 'Kathua',
  Kendrapara: 'Kendrapara',
  Kendujhar: 'Kendujhar',
  Kheda: 'Kheda',
  Khordha: 'Khordha',
  Kishtwar: 'Kishtwar',
  Kolar: 'Kolar',
  Kolkata: 'Kolkata',
  Korba: 'Korba',
  Kota: 'Kota',
  Kushinagar: 'Kushinagar',
  Kutch: 'Kachchh',
  Lakhisarai: 'Lakhisarai',
  Lalitpur: 'Lalitpur',
  Lucknow: 'Lucknow',
  Maharajganj: 'Siwan',
  Mahasamund: 'Mahasamund',
  Mahendragarh: 'Mahendragarh',
  Mahoba: 'Mahoba',
  Mandla: 'Mandla',
  Mathura: 'Mathura',
  Mayurbhanj: 'Mayurbhanj',
  Mehsana: 'Mahesana',
  Morena: 'Morena',
  'Mumbai suburban': 'Mumbai Suburban',
  Munger: 'Munger',
  Mysore: 'Mysuru',
  Nadia: 'Nadia',
  Nagaur: 'Nagaur',
  Nalanda: 'Nalanda',
  Nanded: 'Nanded',
  Nashik: 'Nashik',
  Navsari: 'Navsari',
  Nawada: 'Nawada',
  'North Delhi': 'North Delhi',
  'North East Delhi': 'North East Delhi',
  Pali: 'Pali',
  Palwal: 'Palwal',
  Panchkula: 'Panchkula',
  Panchmahal: 'Panch Mahals',
  Panipat: 'Panipat',
  Patan: 'Patan',
  Patna: 'Patna',
  'Pauri Garhwal': 'Pauri Garhwal',
  Poonch: 'Poonch',
  Pune: 'Pune',
  'Purba Medinipur': 'Purba Medinipur',
  Puri: 'Puri',
  Purulia: 'Purulia',
  Raebareli: 'Rae Bareli',
  Raigad: 'Raigad',
  Raipur: 'Raipur',
  Raisen: 'Raisen',
  Rajauri: 'Rajouri',
  Rajgarh: 'Rajgarh',
  Rajkot: 'Rajkot',
  Ramanagara: 'Ramanagara',
  Ramban: 'Ramban',
  Ratnagiri: 'Ratnagiri',
  Reasi: 'Reasi',
  Rewa: 'Rewa',
  Rewari: 'Rewari',
  Rohtak: 'Rohtak',
  Rohtas: 'Rohtas',
  Rudraprayag: 'Rudra Prayag',
  Sabarkantha: 'Sabar Kantha',
  Sagar: 'Sagar',
  Samba: 'Samba',
  Sangli: 'Sangli',
  'Sant Kabir Nagar': 'Sant Kabir Nagar',
  Satna: 'Satna',
  Sehore: 'Sehore',
  Seoni: 'Seoni',
  Shahdol: 'Shahdol',
  Shahjahanpur: 'Shahjahanpur',
  Shimoga: 'Shivamogga',
  Shivpuri: 'Shivpuri',
  Siddharthnagar: 'Siddharthnagar',
  Sikar: 'Sikar',
  Sirohi: 'Sirohi',
  Sirsa: 'Sirsa',
  Sonipat: 'Sonipat',
  'South 24 Parganas': 'South 24 Parganas',
  'South Delhi': 'South Delhi',
  Surendranagar: 'Surendranagar',
  Surguja: 'Surguja',
  'Tehri Garhwal': 'Tehri Garhwal',
  Thane: 'Thane',
  Thiruvananthapuram: 'Thiruvananthapuram',
  Thrissur: 'Thrissur',
  Udhampur: 'Udhampur',
  Umaria: 'Umaria',
  Uttarkashi: 'Uttar Kashi',
  Vadodara: 'Vadodara',
  Valsad: 'Valsad',
  Vyara: 'Tapi',
  Wardha: 'Wardha',
  Washim: 'Washim',
  'West Delhi': 'West Delhi',
  'Yamuna Nagar': 'Yamunanagar',
  Begusarai: 'Begusarai',
  Ranchi: 'Ranchi',
  Porbandar: 'Porbandar',
  Surat: 'Surat',
  Udaipur: 'Udaipur',
};
