export const oldNewStateMap = {
  Gujarat: 'Gujarat',
  Punjab: 'Punjab',
  'West Bengal': 'West Bengal',
  'Madhya Pradesh': 'Madhya Pradesh',
  Delhi: 'Delhi',
  Uttarakhand: 'Uttarakhand',
  'Andhra Pradesh': 'Andhra Pradesh',
  Haryana: 'Haryana',
  Maharashtra: 'Maharashtra',
  Rajasthan: 'Rajasthan',
  'Jammu and Kashmir': 'Jammu And Kashmir',
  Kerala: 'Kerala',
  'Uttar Pradesh': 'Uttar Pradesh',
  Karnataka: 'Karnataka',
  Bihar: 'Bihar',
  Chhattisgarh: 'Chhattisgarh',
  Orissa: 'Odisha',
  Jharkhand: 'Jharkhand',
};
